### ISSUE TITLE
As a user in desktop listing type selection, I see empty space to the bottom and right of the coming soon containers

### ISSUE THREAD

**Issue by Ummbojumbo** [okonomione/MidnightMerchant#179]
**Context**
As a user in desktop listing type selection, I see empty space to the bottom and right of the coming soon containers 

**Action**
N/A

**Result**
N/A

**Acceptance criteria**
[ ] Blue borders have 100% with and height not 110%

**Links**
N/A

**Other**
```CSS
.comin-soon_comingSoon__AGZ\+e .comin-soon_innerContainer__5EB9N {
    border: 7px solid #00b1d8;
    border: 7px solid var(--blue, #00b1d8);
    border-radius: 25px;
    border-radius: 19px;
    box-shadow: 0 0 11px 0 #000000ba;
    display: flex;
    flex-direction: column;
    height: 100%;
    position: absolute;
    top: -10px;
    transition: all .3s ease-in-out;
    width: 100%;
    z-index: 1;
}
```
